apps/home/models.py
from apps import db # Import the SQLAlchemy database instance
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy() 

class Worker(db.Model):
    id = db.Column(db.Integer, primary_key=True)                        #
    FIO = db.Column(db.String(80), unique=True, nullable=False)         # фио
    location = db.Column(db.String(80), nullable=False)                 # адрес локации
    grade = db.Column(db.String(80), nullable=False)                    # грейд
    location_text = db.Column(db.String(80), nullable=False)

class Tasks(db.Model):
    type = db.Column(db.Integer, primary_key=True)                      # тип
    title = db.Column(db.String(100), nullable=False)                   # название
    priority = db.Column(db.String(30), nullable=False)                 # приоритет
    lead_time = db.Column(db.Float, nullable=False)                     # время
    condition = db.Column(db.String(120), nullable=False)               # условие
    level = db.Column(db.String(30), nullable=False)                    # требуемый уровень сотрудника

class Points(db.Model):
    id = db.Column(db.Integer, primary_key=True)                        # номер точки
    address = db.Column(db.String(100), nullable=False)                 # адрес точки
    connected = db.Column(db.String(80), nullable=False)                # когда подключена точка
    delivered = db.Column(db.Boolean, default=False)                    # карты и материалы доставлены
    days_last_card = db.Column(db.Integer)                              # кол-во дней после выдачи последней карты
    num_approved_app = db.Column(db.Integer)                            # кол-во одобренных заявок
    num_card = db.Column(db.Integer)                                    # кол-во выданных карт
    address_text = db.Column(db.String(100), nullable=False)
    delivered_text = db.Column(db.String(10), nullable=False)


class Undistr_tasks(db.Model):
    idt = db.Column(db.String(100), primary_key=True)
    task_type = db.Column(db.Integer, nullable=False)                   # тип задачи
    task_title = db.Column(db.String(100), nullable=False)              # название задачи
    task_priority = db.Column(db.String(30), nullable=False)            # приоритет задачи
    task_lead_time = db.Column(db.Float, nullable=False)                # время выполнения задачи
    task_level = db.Column(db.String(30), nullable=False)               # требуемый уровень сотрудника для выполнения задачи
    point_id = db.Column(db.Integer, nullable=False)                    # номер точки
    point_address = db.Column(db.String(100), nullable=False)           # адрес точки
    date = db.Column(db.String(10), nullable=False)                     # дата создания задачи


class Full_tasks(db.Model):
    idt = db.Column(db.String(100), primary_key=True)
    task_type = db.Column(db.Integer, nullable=False)                   # тип задачи
    task_title = db.Column(db.String(100), nullable=False)              # название задачи
    task_priority = db.Column(db.String(30), nullable=False)            # приоритет задачи
    task_lead_time = db.Column(db.Float, nullable=False)                # время выполнения задачи + время в пути (если задача уже назначена)
    task_level = db.Column(db.String(30), nullable=False)               # требуемый уровень сотрудника для выполнения задачи
    point_id = db.Column(db.Integer, nullable=False)                    # номер точки
    point_address = db.Column(db.String(100), nullable=False)           # адрес точки
    date = db.Column(db.String(10), nullable=False)                     # дата создания задачи
    status = db.Column(db.String(10), nullable=False)                   # статус задачи ('finish' - завершена,
    comment = db.Column(db.String(100))                                 # 'active' - в расписании сотрудника,
    worker_id = db.Column(db.Integer)                                   # 'wait' - в очереди,
                                                                        # 'problem' - имеются проблемы с задачей)
class Worker_last_location(db.Model):
    id = db.Column(db.Integer, primary_key=True)                        #
    last_location = db.Column(db.String(80), nullable=False)                 # адрес последней локации

class Schedule(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.String(10), nullable=False)  # дата в формате 'гггг_мм_дд'
    schedule = db.Column(db.LargeBinary, nullable=False)  # JSON данные как BLOB
    
class Users(db.Model):
    id=db.Column(db.Integer, primary_key=True,autoincrement=True)
    username = db.Column(db.String(64), unique=True)
    role = db.Column(db.String(64), unique=True)
    worker_FIO = db.Column(db.Integer)
    password = db.Column(db.LargeBinary)


    

apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
from apps.home import blueprint
from flask import render_template, request
from flask_login import login_required
from jinja2 import TemplateNotFound
from flask import session,Blueprint
from apps import db
from apps.home.models import Worker, Users, Full_tasks, Schedule, Points, Tasks
from apps.home.function import line_tasks, distribute_tasks, get_schedule_for_workers_on_day, address_to_coordinates, \
    add_task, excel_in_bd,create_report
from flask import request, jsonify
import json
from collections import defaultdict
from sqlalchemy import func
from flask import send_file
# line_tasks()                          # создание очереди
# distribute_tasks()                    # распределение задач
# TODO: для blueprint задач доавить всязь двух таблиц(установление юзера по задачам)
#Получение имени пользователя и роли    
def role():
    username = session.get('username')
    role = session.get('role')
    return username, role

@blueprint.route('/index')
@login_required
def index():
    username, user_role = role()
    users=Users.query.all()
    user_count = Users.query.with_entities(Users.username).count()
    worker_count = Users.query.with_entities(Worker.FIO).count()
    tasks_count = Users.query.with_entities(Tasks.title).count()
    full_tasks_count = Users.query.with_entities(Full_tasks.idt).count()
    schedules = Schedule.query.all()

    # Создаем словарь для хранения количества id для каждой даты
    count_by_date = defaultdict(int)

    # Проходим по каждой записи
    for schedule in schedules:
        date = schedule.date
        schedule_data = json.loads(schedule.schedule)

        # Проходим по каждому id в расписании и увеличиваем счетчик
        for _, data in schedule_data.items():
            for _, id_value in data['schedule'].items():
                count_by_date[date] += 1

    # Преобразуем словарь в массив кортежей
    result_array = list(count_by_date.items())
    tasks_per_day = result_array
    print(tasks_per_day)
    return render_template('home/index.html', segment='index', username=username, role=user_role,users=users,user_count=user_count,worker_count=worker_count,tasks_count=tasks_count,full_tasks_count = full_tasks_count,tasks_per_day=tasks_per_day)

@blueprint.route('/<template>', methods=['GET', 'POST'])
@login_required
def route_template(template):
    username,user_role=role() 
    try:
        if not template.endswith('.html'):
            template += '.html'
        segment = get_segment(request)
        if template == 'tables.html':
            workers=Worker.query.all()[:3]
            users=Users.query.all()[:3]
            points=Points.query.all()[:3]
            return render_template("home/" + template, segment=segment, username=username, role=user_role, workers=workers,users=users,points=points)
        if template == 'workers.html':
            workers=Worker.query.all()
            return render_template("home/" + template, segment=segment, username=username, role=user_role, workers=workers)
        if template == 'users.html':
            users=Users.query.all()
            for user in users:
                user.password='***'
            return render_template("home/" + template, segment=segment, username=username, role=user_role, users=users)
        if template == 'points.html':
            points=Points.query.all()
            return render_template("home/" + template, segment=segment, username=username, role=user_role, points=points)
        if template == 'calendar.html':
            schedules = Schedule.query.all()
            dates = [schedule.date for schedule in schedules]
            return render_template("home/" + template, segment=segment, username=username, role=user_role, schedule=dates)
        if template == 'constructor.html':
            data = []
            entered_values = []
            import re
            def process_expression(input_str):
                regex = re.compile(r'\((.*?)\)')

                def process_sub_expression(sub_expr):

                    if "num_approved_app" in sub_expr or "num_card" in sub_expr:

                        sub_expr = sub_expr.replace('(', '').replace(')', '')

                        return f'CAST({sub_expr})'
                    return sub_expr

                result = regex.sub(lambda match: process_sub_expression(match.group(1)), input_str)

                return result

            def transform_str(resArr):
                if '| )' in resArr:
                    resArr = resArr.replace(' | )', ') | ')
                if '& )' in resArr:
                    resArr = resArr.replace(' & )', ') & ')
                return resArr

            def res_arr_form_maker(resArr):
                res_string = ''
                try:
                    for i in resArr:
                        if '|' in i:
                            i = i.replace(' |','')
                            res_string += f"({i}) | "
                        elif '&' in i:
                            i = i.replace(' &','')
                            res_string += f"({i}) & "
                        elif '(' in i:
                            res_string+='('
                        elif ')' in i:
                            res_string+=')'
                        else:
                            print('ne I ne & ne srabotalo')
                    # print(res_string[:-2])
                except Exception:
                    pass
                return process_expression(transform_str(res_string[:-2]))
            
            def check_bad_ending(expression):
                expression = expression.rstrip()

                if expression.endswith("&") or expression.endswith("|"):
                    # Если да, удаляем последний символ
                    expression = expression[:-1]

                return expression

            def replace_values(input_str):
                cur_dict = {
                "Points.id": "Номер",
                "Points.address": "Адрес",
                "Points.connected": "Когда подключена точка?",
                "Points.delivered": "Карты и материалы доставлены?",
                "Points.days_last_card": "Количество дней после выдачи последней карты",
                "Points.num_approved_app AS FLOAT": "Количество одобренных заявок",
                "Points.num_card AS FLOAT": "Количество выданных карт"
            }
                reversed_dict = {v: k for k, v in cur_dict.items()}
                for key, value in reversed_dict.items():
                    input_str = input_str.replace(key, value)
                return input_str
            
            if request.method == 'POST':
                priority = request.form.get('prioritySelect')
                task_name = request.form.get('taskname')
                dlit = request.form.get('dlit')
                resArr = request.form.get('resArr')
                selected_levels = request.form.getlist('levels')
                
                if resArr:
                    resArr = json.loads(resArr)
                else:
                    resArr = []
                entered_values.extend([task_name, priority, dlit, replace_values(check_bad_ending(res_arr_form_maker(resArr))), selected_levels])

                add_task(task_name, priority, dlit, replace_values(check_bad_ending(res_arr_form_maker(resArr))), str(selected_levels).replace('[','').replace(']','').replace(',',' or'))
                # def add_task(title, priority, lead_time, condition, level):
            return render_template("home/" + template, segment=segment, username=username, role=user_role)
        
        if template == 'billing.html':
            data = []
            tasks=Tasks.query.all()
            full_tasks = Full_tasks.query.all()
            for full_task in full_tasks:
                worker = db.session.query(Worker).filter(Worker.id == full_task.worker_id).first()
                task_data = {
                    'idt': full_task.idt,
                    'fio': worker.FIO,
                    'task_title': full_task.task_title,
                    'task_priority': full_task.task_priority,
                    'task_lead_time': full_task.task_lead_time,
                    'point_address': full_task.point_address,
                    'task_status': full_task.status,
                    'task_comment': full_task.comment,
                }
                data.append(task_data)
                entered_values = []

            # import re
            # def process_expression(input_str):
            #     regex = re.compile(r'\((.*?)\)')

            #     def process_sub_expression(sub_expr):

            #         if "num_approved_app" in sub_expr or "num_card" in sub_expr:

            #             sub_expr = sub_expr.replace('(', '').replace(')', '')

            #             return f'CAST({sub_expr})'
            #         return sub_expr

            #     result = regex.sub(lambda match: process_sub_expression(match.group(1)), input_str)

            #     return result

            
            # def transform_str(resArr):
            #     if '| )' in resArr:
            #         resArr = resArr.replace(' | )', ') | ')
            #     if '& )' in resArr:
            #         resArr = resArr.replace(' & )', ') & ')
            #     return resArr

            # def res_arr_form_maker(resArr):
            #     # print(resArr)
            #     res_string = ''
            #     try:
            #         for i in resArr:
            #             if '|' in i:
            #                 i = i.replace(' |','')
            #                 res_string += f"({i}) | "
            #             elif '&' in i:
            #                 i = i.replace(' &','')
            #                 res_string += f"({i}) & "
            #             elif '(' in i:
            #                 res_string+='('
            #             elif ')' in i:
            #                 res_string+=')'

apps/templates/home/calendar.html
{% extends "layouts/base.html" %}

{% block title %} Календарь {% endblock %} 

{% block stylesheets %}
<style>
#dateDropdown {
    background-color: white;
    color: #7b809a; /* Цвет текста внутри селекта */
    border: 1px solid #ff4b5f; /* Цвет обводки */
    border-radius: 8px; /* Радиус скругления краев */
    text-align-last: center; /* Выравнивание текста по центру */
}
</style>
{% endblock stylesheets %}

{% block content %}



<div class="container-fluid py-4">
    <div class="row">
      <div class="col">
        <label for="dateDropdown" class="form-label"><h5>Выберите дату</h5></label>
        <select class="form-select" id="dateDropdown" name="selectedDate" style="background-color: white; border: 1px solid #ff4b5f; border-radius: 5px;">
            {% for date in schedule %}
                <option value="{{ date }}">{{ date }}</option>
            {% endfor %}
        </select>        
      </div>
    </div>
  </div>
            <div class="container-fluid py-4">
                <div class="row">
<div class="container-fluid" id="contentContainer">
</div>
</div>
</div>
{% endblock content %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var dateDropdown = document.getElementById('dateDropdown');
        var contentContainer = document.getElementById('contentContainer');

        dateDropdown.addEventListener('change', function () {
            var selectedDate = dateDropdown.value;

            axios.get(`/endpoint?date=${selectedDate}`)
                .then(function (response) {
                    clearTables();
                    addTables(response.data);
                })
                .catch(function (error) {
                    console.error('Error:', error);
                });
        });

        // При загрузке страницы показываем таблицы для первой даты
        showTablesForInitialDate();

        function showTablesForInitialDate() {
            var initialDate = dateDropdown.options[0].value;

            axios.get(`/endpoint?date=${initialDate}`)
                .then(function (response) {
                    addTables(response.data);
                })
                .catch(function (error) {
                    console.error('Error:', error);
                });
        }

        function addTables(data) {
            for (var workerData of data) {
                var intervals = workerData['intervals'];

                var workerContainer = document.createElement('div');
                workerContainer.className = 'container-fluid py-4';
                workerContainer.innerHTML = `
                    <div class="row">
                        <div class="col-md-12 mx-auto">
                            <div class="card my-4">
                                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                                    <div class="bg-gradient-primary shadow-success border-radius-lg pt-4 pb-3">
                                        <h6 class="text-white text-capitalize ps-3">${workerData['worker']}</h6>
                                    </div>
                                </div>
                                <div class="card-body px-0 pb-2">
                                    <div class="table-responsive p-0">
                                        <table class="table align-items-center mb-0">
                                            <thead>
                                                <tr>
                                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7" style="text-align: left;">Интервал времени</th>
                                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Название задачи</th>
                                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Адрес</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                ${intervals ? 
                                                    Object.entries(intervals).map(([interval, item]) => `
                                                        <tr>
                                                            <td style="text-align: left; padding-left: 23px;">${interval}</td>
                                                            <td style="padding-right: 20px;">${item.task_title}</td>
                                                            <td style="padding-right: 20px;">${item.point_address}</td>
                                                        </tr>
                                                    `).join('') :
                                                    '<tr><td colspan="5" style="text-align: center;">Нет доступных интервалов</td></tr>'
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                `;

                contentContainer.appendChild(workerContainer);
            }
        }

        function clearTables() {
            contentContainer.innerHTML = '';
        }
    });
</script>
{% endblock javascripts %}

apps/templates/home/tables.html
{% extends "layouts/base.html" %}

{% block title %} Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style>
.limited-text {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 10px; /* Измените это значение на ваше усмотрение */
  cursor: pointer;}
</style>
{% endblock stylesheets %}

{% block content %}

<div class="container-fluid py-4">
  <div class="row">
    <!-- Первая колонка (пользователи) -->
    <div class="col-md-6">
      <div class="card my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-primary shadow-success border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize ps-3">Пользователи</h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7" style="text-align: left;">Имя пользователя</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Роль</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Пароль</th>
                  <th class="text-secondary opacity-7"></th>
                  <th class="text-secondary opacity-7"></th>
                </tr>
              </thead>
              <tbody>
                {% for user in users %}
                  <tr>
                    <td style="text-align: left; padding-left: 23px;">{{ user.username }}</td>
                    <td style="padding-right: 20px;">{{ user.role }}</td>
                    <td style="padding-right: 20px;">****</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            <a href="{{ url_for('home_blueprint.route_template', template='users.html') }}" class="btn btn-success"
               style="background-color: #ff4b5f; color: white;margin-top:20px; margin-right: 20px; float: right;">
               Перейти к таблице
            </a>
            <div id="message"></div>
          </div>
        </div>
      </div>
    </div>

    <!-- Вторая колонка (сотрудники) -->
    <div class="col-md-6">
      <div class="card my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize ps-3">Сотрудники</h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7" style="text-align: left;">ФИО</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Местоположение</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Уровень</th>
                  <th class="text-secondary opacity-7"></th>
                  <th class="text-secondary opacity-7"></th>
                </tr>
              </thead>
              <tbody>
                {% for worker in workers %}
                  <tr>
                    <td style="text-align: left; padding-left: 23px;">{{ worker.FIO }}</td>
                    <td  class="limited-text" style="padding-right: 20px;">{{ worker.location_text }}</td>
                    <td style="padding-right: 20px;">{{ worker.grade }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            <a href="{{ url_for('home_blueprint.route_template', template='workers.html') }}" class="btn btn-info"
               style="background-color: #ff4b5f; color: white; margin-top:20px; margin-right: 20px; float: right;">
               Перейти к таблице
            </a>
            <div id="message"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid py-4">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-primary shadow-success border-radius-lg pt-4 pb-3">
            <h6 class="text-white ps-3">Агентские точки</h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7" style="text-align: left;">Адрес</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Когда подключена <br>точка</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Доставлены ли <br>материалы</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Кол-во дней после <br>выдачи последней карты</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Кол-во одобренных <br>заявок</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2" style="text-align: left;">Кол-во выданных<br> карт</th>
                </tr>
              </thead>
              <tbody>
                {% for point in points %}
                  <tr>
                    <td class="limited-text" style="text-align: left; padding-left: 23px;">{{ point.address_text }}</td>
                  <td style="padding-right: 20px;">{{ point.connected }}</td>
                  <td style="padding-right: 20px;">{{ point.delivered_text }}</td>
                   <td style="padding-right: 20px;">{{ point.days_last_card }}</td>
                  <td style="padding-right: 20px;">{{ point.num_approved_app }}</td>
                  <td style="padding-right: 20px;">{{ point.num_card }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            <a href="{{ url_for('home_blueprint.route_template', template='points.html') }}" class="btn btn-primary"
               style="background-color: #ff4b5f; color: white; margin-top:20px; margin-right: 20px; float: right;">
               Перейти к таблице
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>











{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
  document.addEventListener('DOMContentLoaded', function () {
    // Обработчик события для отображения полного текста при наведении
    document.querySelectorAll('.limited-text').forEach(function (cell) {
      cell.addEventListener('mouseover', function () {
        this.style.whiteSpace = 'normal';
        this.style.overflow = 'visible';
        this.style.maxWidth = 'none';
      });
  
      cell.addEventListener('mouseout', function () {
        this.style.whiteSpace = 'nowrap';
        this.style.overflow = 'hidden';
        this.style.textOverflow = 'ellipsis';
        this.style.maxWidth = '150px'; // Измените это значение на ваше усмотрение
      });
    });
  });


  document.addEventListener('click', function (event) {
    if (event.target.id === 'add-button') {
      // Обработка нажатия на кнопку "Добавить"
      // Здесь вы можете выполнить необходимые действия, такие как добавление новой строки в таблицу
    }
  });
  document.addEventListener('click', function (event) {
    if (event.target.classList.contains('edit-button')) {
      const editButton = event.target;
      const saveButton = editButton.nextElementSibling;
      const row = editButton.closest('tr');
      
      // Проверка, если поле редактируется, то не менять его
      const contentEditableCells = row.querySelectorAll('[contenteditable="true"]');
      if (contentEditableCells.length === 0) {
        row.querySelectorAll('[contenteditable="false"]').forEach(cell => {
          cell.contentEditable = 'true';
        });
      }
      
      // Переключите видимость кнопок
      editButton.style.display = 'none';
      saveButton.style.display = 'inline';
    } else if (event.target.classList.contains('save-button')) {
      const saveButton = event.target;
      const editButton = saveButton.previousElementSibling;
      const row = saveButton.closest('tr');
      
      // Переключите contenteditable обратно на false
      row.querySelectorAll('[contenteditable="true"]').forEach(cell => {
        cell.contentEditable = 'false';
      });
      
      // Здесь вы можете получить новые значения из ячеек с contenteditable="true" и отправить их на сервер
      const updatedData = {};
      row.querySelectorAll('[contenteditable="true"]').forEach(cell => {
        const fieldName = cell.dataset.name;
        const value = cell.innerText;
        updatedData[fieldName] = value;
      });
  
      // Отправьте данные на сервер
      fetch('/update_worker/' + workerId, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(updatedData),
      })
      .then(response => response.json())
      .then(data => {
        // Обработка успешного обновления данных
        console.log('Данные успешно обновлены:', data);
      
        // Добавьте `console.log` с выводом "1"
        console.log('1');
      })
      .catch(error => {
        // Обработка ошибок
        console.error('Ошибка при обновлении данных:', error);
      });
      
      .then(response => response.json())
      .then(data => {
        // Данные успешно обновлены, можно выполнить какие-либо действия
        console.log('Данные успешно обновлены:', data);
      })
      .catch(error => {
        // Обработка ошибок
        console.error('Ошибка при обновлении данных:', error);
      });
      saveButton.style.display = 'none';
editButton.style.display = 'inline';

// Вставьте сообщение в элемент "message"
const messageElement = document.getElementById('message');
messageElement.innerHTML = 'Данные успешно обновлены';

// Очистите сообщение через некоторое время, например, через 3 секунды
setTimeout(() => {
  messageElement.innerHTML = '';
}, 3000);
  });
  

</script>




{% endblock javascripts %}